# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/debian/Project/smon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/debian/Project/smon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/debian/Project/smon/CMakeFiles /home/debian/Project/smon//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/debian/Project/smon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named smon

# Build rule for target.
smon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 smon
.PHONY : smon

# fast build rule for target.
smon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/build
.PHONY : smon/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/main.cpp.s
.PHONY : main.cpp.s

src/CpuMonitoring.o: src/CpuMonitoring.cpp.o
.PHONY : src/CpuMonitoring.o

# target to build an object file
src/CpuMonitoring.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/CpuMonitoring.cpp.o
.PHONY : src/CpuMonitoring.cpp.o

src/CpuMonitoring.i: src/CpuMonitoring.cpp.i
.PHONY : src/CpuMonitoring.i

# target to preprocess a source file
src/CpuMonitoring.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/CpuMonitoring.cpp.i
.PHONY : src/CpuMonitoring.cpp.i

src/CpuMonitoring.s: src/CpuMonitoring.cpp.s
.PHONY : src/CpuMonitoring.s

# target to generate assembly for a file
src/CpuMonitoring.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/CpuMonitoring.cpp.s
.PHONY : src/CpuMonitoring.cpp.s

src/DiskMonitoring.o: src/DiskMonitoring.cpp.o
.PHONY : src/DiskMonitoring.o

# target to build an object file
src/DiskMonitoring.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/DiskMonitoring.cpp.o
.PHONY : src/DiskMonitoring.cpp.o

src/DiskMonitoring.i: src/DiskMonitoring.cpp.i
.PHONY : src/DiskMonitoring.i

# target to preprocess a source file
src/DiskMonitoring.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/DiskMonitoring.cpp.i
.PHONY : src/DiskMonitoring.cpp.i

src/DiskMonitoring.s: src/DiskMonitoring.cpp.s
.PHONY : src/DiskMonitoring.s

# target to generate assembly for a file
src/DiskMonitoring.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/DiskMonitoring.cpp.s
.PHONY : src/DiskMonitoring.cpp.s

src/HandleEvent.o: src/HandleEvent.cpp.o
.PHONY : src/HandleEvent.o

# target to build an object file
src/HandleEvent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/HandleEvent.cpp.o
.PHONY : src/HandleEvent.cpp.o

src/HandleEvent.i: src/HandleEvent.cpp.i
.PHONY : src/HandleEvent.i

# target to preprocess a source file
src/HandleEvent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/HandleEvent.cpp.i
.PHONY : src/HandleEvent.cpp.i

src/HandleEvent.s: src/HandleEvent.cpp.s
.PHONY : src/HandleEvent.s

# target to generate assembly for a file
src/HandleEvent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/HandleEvent.cpp.s
.PHONY : src/HandleEvent.cpp.s

src/MemoryMonitoring.o: src/MemoryMonitoring.cpp.o
.PHONY : src/MemoryMonitoring.o

# target to build an object file
src/MemoryMonitoring.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/MemoryMonitoring.cpp.o
.PHONY : src/MemoryMonitoring.cpp.o

src/MemoryMonitoring.i: src/MemoryMonitoring.cpp.i
.PHONY : src/MemoryMonitoring.i

# target to preprocess a source file
src/MemoryMonitoring.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/MemoryMonitoring.cpp.i
.PHONY : src/MemoryMonitoring.cpp.i

src/MemoryMonitoring.s: src/MemoryMonitoring.cpp.s
.PHONY : src/MemoryMonitoring.s

# target to generate assembly for a file
src/MemoryMonitoring.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/MemoryMonitoring.cpp.s
.PHONY : src/MemoryMonitoring.cpp.s

src/Overview.o: src/Overview.cpp.o
.PHONY : src/Overview.o

# target to build an object file
src/Overview.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/Overview.cpp.o
.PHONY : src/Overview.cpp.o

src/Overview.i: src/Overview.cpp.i
.PHONY : src/Overview.i

# target to preprocess a source file
src/Overview.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/Overview.cpp.i
.PHONY : src/Overview.cpp.i

src/Overview.s: src/Overview.cpp.s
.PHONY : src/Overview.s

# target to generate assembly for a file
src/Overview.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/Overview.cpp.s
.PHONY : src/Overview.cpp.s

src/ProcessActivityMonitoring.o: src/ProcessActivityMonitoring.cpp.o
.PHONY : src/ProcessActivityMonitoring.o

# target to build an object file
src/ProcessActivityMonitoring.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/ProcessActivityMonitoring.cpp.o
.PHONY : src/ProcessActivityMonitoring.cpp.o

src/ProcessActivityMonitoring.i: src/ProcessActivityMonitoring.cpp.i
.PHONY : src/ProcessActivityMonitoring.i

# target to preprocess a source file
src/ProcessActivityMonitoring.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/ProcessActivityMonitoring.cpp.i
.PHONY : src/ProcessActivityMonitoring.cpp.i

src/ProcessActivityMonitoring.s: src/ProcessActivityMonitoring.cpp.s
.PHONY : src/ProcessActivityMonitoring.s

# target to generate assembly for a file
src/ProcessActivityMonitoring.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/ProcessActivityMonitoring.cpp.s
.PHONY : src/ProcessActivityMonitoring.cpp.s

src/TitleComponent.o: src/TitleComponent.cpp.o
.PHONY : src/TitleComponent.o

# target to build an object file
src/TitleComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/TitleComponent.cpp.o
.PHONY : src/TitleComponent.cpp.o

src/TitleComponent.i: src/TitleComponent.cpp.i
.PHONY : src/TitleComponent.i

# target to preprocess a source file
src/TitleComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/TitleComponent.cpp.i
.PHONY : src/TitleComponent.cpp.i

src/TitleComponent.s: src/TitleComponent.cpp.s
.PHONY : src/TitleComponent.s

# target to generate assembly for a file
src/TitleComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smon.dir/build.make CMakeFiles/smon.dir/src/TitleComponent.cpp.s
.PHONY : src/TitleComponent.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... smon"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/CpuMonitoring.o"
	@echo "... src/CpuMonitoring.i"
	@echo "... src/CpuMonitoring.s"
	@echo "... src/DiskMonitoring.o"
	@echo "... src/DiskMonitoring.i"
	@echo "... src/DiskMonitoring.s"
	@echo "... src/HandleEvent.o"
	@echo "... src/HandleEvent.i"
	@echo "... src/HandleEvent.s"
	@echo "... src/MemoryMonitoring.o"
	@echo "... src/MemoryMonitoring.i"
	@echo "... src/MemoryMonitoring.s"
	@echo "... src/Overview.o"
	@echo "... src/Overview.i"
	@echo "... src/Overview.s"
	@echo "... src/ProcessActivityMonitoring.o"
	@echo "... src/ProcessActivityMonitoring.i"
	@echo "... src/ProcessActivityMonitoring.s"
	@echo "... src/TitleComponent.o"
	@echo "... src/TitleComponent.i"
	@echo "... src/TitleComponent.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

